SELECT
CONCAT(
'INSERT INTO TBWMWCONFIGCAMPOINTEG(
	NMENTIDADE, NMCAMPOSISTEMA, NMCAMPOERP, DSVALORFIXO, DSVALORSECAMPOVAZIO, NUORDEM, DSMASCARA, DSEXPRESSAO, FLTIPOALTERACAO, FLIGNORAQUANDOVAZIO, FLATIVO
) VALUES(''',
	NMENTIDADE, ''',''', NMCAMPOSISTEMA, ''',''', NMCAMPOERP, ''',''', DSVALORFIXO, ''',''', DSVALORSECAMPOVAZIO, ''',''', NUORDEM, ''',''', DSMASCARA, ''',''', REPLACE(DSEXPRESSAO, '''', ''''''), ''',''', FLTIPOALTERACAO, ''',''', FLIGNORAQUANDOVAZIO, ''',''', FLATIVO, '''',
');')
FROM TBWMWCONFIGCAMPOINTEG 
WHERE 
	FLATIVO = 'S' 
AND NMENTIDADE != 'PEDIDOERP';


SELECT
CONCAT('UPDATE TBWMWVALORPARAMETRO
SET VLPARAMETRO = ''', VLPARAMETRO, '''
WHERE
	CDSISTEMA = ''', CDSISTEMA, '''
AND CDPARAMETRO = ''', CDPARAMETRO, '''
AND NMENTIDADE = ''', NMENTIDADE, '''
AND VLCHAVE = ''', VLCHAVE, ''';')
FROM TBWMWVALORPARAMETRO
WHERE
	FLATIVO = 'S';